[vmware]
mode = "gui"
interface = "virbr0"
vmrun_path = "/usr/bin/vmrun"

[[machines]]
name = "xpsp3"
vmx_path = "/data/vms/xpsp3/xpsp3.vmx"
snapshot = "Base"
platform = "Windows"
ip = "10.152.152.55"
arch = "x64"
# tags = []
# interface = ""
# result_server_ip = ""
# result_server_port = ""

[[machines]]
name = "win7x64sp1"
vmx_path = "/data/vms/win7x64sp1/win7x64sp1.vmx"
snapshot = "clean"
platform = "windows"
ip = "10.152.152.60"
arch = "x64"
# tags = []
# interface = ""
# result_server_ip = ""
# result_server_port = ""
