name = "windows-sandbox"
description = "Windows Sandbox for Malware Analysis"
platform = "windows"

[packer]
template = "base.pkr.hcl"

[packer.vars]
# Common variables
vm_name = "win10-sandbox"
os_version = "10"
cpu_num = "2"
memory = "4096"

# VMware specific
vcenter_server = "vcenter.local"
vsphere_username = "administrator@vsphere.local"
vsphere_password = "secret"
vmware_network = "Sandbox_Network"

# VirtualBox specific
vbox_network = "vboxnet0"
vbox_guest_os_type = "Windows10_64"

# KVM specific
libvirt_uri = "qemu:///system"
libvirt_network = "default"

[ansible]
playbook = "playbooks/windows.yml"

[ansible.vars]
sandbox_tools = "procmon,processhacker,wireshark,pestudio,x64dbg"
network_isolation = "true"
monitoring_server = "192.168.1.100"
