type = "kvm"
uri = "test"
cpus = 2
memory = 32
video_memory = 32

[network]
name = "testnet"
interface = "wlo1"
address_range = "10.10.10.0"
bridge = ""
nat_enabled = false

[storage]
path = "/home/shard/Downloads/malbox/"
storage_type = "Raw"
default_size_gb = 32
bus = "virtio"

[[machines]]
name = "test"
platform = "windows"
arch = "X64"
ip = "10.10.10.1"
reserved = true
cpus = 4
memory = 4096

