[package]
name = "malbox-hashing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc32fast = "1.4.0"
md5 = "0.7.0"
sha1 = "0.10.6"
sha2 = "0.10.8"
ssdeep = "0.6.0"
