CREATE TABLE "samples" (
    id bigint generated by default as identity,
    file_size integer NOT NULL,
    file_type varchar NOT NULL,
    md5 varchar NOT NULL,
    crc32 varchar NOT NULL,
    sha1 varchar NOT NULL,
    sha256 varchar NOT NULL,
    sha512 varchar NOT NULL,
    ssdeep varchar NOT NULL,
    PRIMARY KEY (id)
);

SELECT trigger_updated_at('"samples"');
