CREATE TABLE "tasks" (
    id bigint generated by default as identity,
    target varchar NOT NULL,
    category varchar NOT NULL,
    timeout bigint DEFAULT 0 NOT NULL,
    priority bigint DEFAULT 1 NOT NULL,
    custom varchar,
    machine varchar,
    package varchar,
    options varchar,
    platform varchar,
    memory boolean NOT NULL,
    enforce_timeout boolean NOT NULL,
    added_on timestamp without time zone NOT NULL,
    started_on timestamp without time zone,
    completed_on timestamp without time zone,
    status status_type DEFAULT 'pending'::status_type NOT NULL,
    sample_id bigint,
    PRIMARY KEY (id),
    FOREIGN KEY (sample_id) REFERENCES samples(id)
);

SELECT trigger_updated_at('"tasks"');
