[package]
name = "malbox-plugin-internal"
version = "0.1.0"
edition = "2024"

[dependencies]
malbox-communication.path = "../malbox-communication"
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
semver.workspace = true
serde.workspace = true
