[package]
name = "malbox-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
malbox-config = { path = "../malbox-config" }
