[package]
name = "malbox-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
abi_stable = "0.11.3"
anyhow.workspace = true
malbox-module-common = { path = "../malbox-module-common" }
