[package]
name = "malbox-communication"
version = "0.1.0"
edition = "2024"

[dependencies]
iceoryx2 = { workspace = true }
iceoryx2-bb-container = { version = "0.5.0" }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
