[package]
name = "malbox-plugin-api"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror.workspace = true
semver.workspace = true
uuid.workspace = true
serde.workspace = true
iceoryx2.workspace = true
async-trait = "0.1.88"
