CREATE TABLE "machines" (
    id integer generated by default as identity,
    name character varying(255) NOT NULL,
    label character varying(255) NOT NULL,
    arch machine_arch NOT NULL,
    platform machine_platform NOT NULL,
    ip character varying(255) NOT NULL,
    tags character varying(255),
    interface character varying(255),
    snapshot character varying(255),
    locked boolean NOT NULL,
    locked_changed_on timestamp without time zone,
    status character varying(255),
    status_changed_on timestamp without time zone,
    result_server_ip character varying(255),
    result_server_port character varying(255),
    reserved boolean NOT NULL DEFAULT false,
    PRIMARY KEY (id)
);

SELECT trigger_updated_at('"machines"');
