[http]
host = "127.0.0.1"
port = 5000

[postgres]
database_url = "postgresql://postgres:password@localhost/malbox-postgres-16"
port = 5432

[debug]
rust_log = "malbox_http=debug,tower_http=debug,sqlx=info,malbox_database=debug,malbox_scheduler=debug,malbox_machinery=debug"

[machinery]
type = "kvm"
