[package]
name = "malbox-abi-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stabby.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json = "1.0.122"
