name: devenv - rust build & test
on:
  push:
    branches: ["main", "dev/*"]
  pull_request:
    branches: ["main", "dev/*"]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: malbox_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libvirt-dev

      - name: Debug environment
        run: |
          dpkg -l | grep libvirt
          ldconfig -p | grep libvirt

      - name: Install sqlx-cli
        run: cargo install sqlx-cli --no-default-features --features native-tls,postgres

      - name: Run migrations
        run: |
          cd malbox-database
          sqlx migrate run
          cd ..
      - name: Update dependencies
        run: cargo update --verbose

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
