name: "Rust Build & Test"

on:
  push:
    branches: ["main", "dev/"]
  pull_request:
    branches: ["main", "dev/"]

jobs:
  tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: devenv shell bash -- -e {0}

    steps:
    - uses: actions/checkout@v4
    
    - uses: cachix/install-nix-action@v26
    
    - uses: cachix/cachix-action@v14
      with:
        name: devenv
    
    - name: Install devenv.sh
      shell: bash
      run: nix profile install nixpkgs#devenv

    - name: Install system dependencies
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y libvirt-dev

    - name: Build the devenv shell and run pre-commit hooks
      run: devenv test

    - name: Start services
      run: devenv up -d

    - name: Wait for PostgreSQL
      run: |
        echo "Waiting for database to be ready..."
        for i in {1..10}; do
          pg_isready -h localhost -p 5432 && break
          echo "Database not ready, waiting..."
          sleep 2
        done

    - name: Setup database
      run: |
        cd malbox-database
        sqlx migrate run

    - name: Run tests
      run: cargo test --verbose
        
    - name: Build project
      run: cargo build --verbose
