name: "Rust Build & Test"
on:
  push:
    branches: ["main", "dev/"]
  pull_request:
    branches: ["main", "dev/"]
jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: malbox_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        shell: devenv shell bash -- -e {0}
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
    - uses: cachix/cachix-action@v14
      with:
        name: devenv
    - name: Install devenv.sh
      shell: bash
      run: nix profile install nixpkgs#devenv
    - name: Install system dependencies
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y libvirt-dev
    - name: Build the devenv shell and run pre-commit hooks
      run: devenv test
    - name: Setup database
      env:
        DATABASE_URL: postgres://postgres:password@localhost:5432/malbox_db
      run: |
        cd malbox-database
        sqlx db migrate
    - name: Run tests
      env:
        DATABASE_URL: postgres://postgres:password@localhost:5432/malbox_db
      run: cargo test --verbose
    - name: Build project
      run: cargo build --verbose
