name: devenv - rust build & test
on:
  push:
    branches: ["main", "dev/*"]
  pull_request:
    branches: ["main", "dev/*"]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Start services and run tests
        shell: devenv shell bash -- -e {0}
        run: |
          # Start postgres service
          devenv processes start postgres

          # Run database migrations
          cd malbox-database
          sqlx migrate run
          cd ..

          # Run tests
          cargo test --verbose

          # Build project
          cargo build --verbose
