name: rust build & test
on:
  push:
    branches: [ "main", "dev/*" ]
  pull_request:
    branches: [ "main", "dev/*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Update dependencies
      run: cargo update --verbose

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
